apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: valentin
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Delete #or Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate
